AllCops:
  RunRailsCops: true
  Excludes:
    - bin/**
    - db/**
    - config/**
    - lib/templates/**
    - vendor/**


Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true
