skip_frontmatter: false

linters:
  CommentControlStatement:
    enabled: true

  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 2

  EmptyControlStatment:
    enabled: true

  ExplicitDiv:
    enabled: true

  LineLength:
    enabled: true
    max: 120

  RuboCop:
    enabled: true
    # These cops are incredibly noisy since the Ruby we extract from Slim
    # templates isn't well-formatted, so we ignore them.
    ignored_cops:
      - Layout/TrailingEmptyLines
      - Lint/EndAlignment
      - Layout/ArgumentAlignment
      - Lint/Void
      - Layout/IndentationWidth

  TagCase:
    enabled: true

  TrailingWhitespace:
    enabled: true
