default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *default

test:
  <<: *default

production: &production
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  rollbar_key: <%= ENV['ROLLBAR_KEY'] %>
  <<: *default

staging:
  <<: *production
